# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('query_helper', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('playStyle', models.CharField(max_length=100)),
                ('playStyleId', models.IntegerField(null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birthdate', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('acceleration', models.IntegerField()),
                ('aggression', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('ballcontrol', models.IntegerField()),
                ('foot', models.CharField(max_length=100)),
                ('skillMoves', models.IntegerField()),
                ('crossing', models.IntegerField()),
                ('curve', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('finishing', models.IntegerField()),
                ('freekickaccuracy', models.IntegerField()),
                ('gkdiving', models.IntegerField()),
                ('gkhandling', models.IntegerField()),
                ('gkkicking', models.IntegerField()),
                ('gkpositioning', models.IntegerField()),
                ('gkreflexes', models.IntegerField()),
                ('headingaccuracy', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('jumping', models.IntegerField()),
                ('longpassing', models.IntegerField()),
                ('longshots', models.IntegerField()),
                ('marking', models.IntegerField()),
                ('penalties', models.IntegerField()),
                ('positioning', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('reactions', models.IntegerField()),
                ('shortpassing', models.IntegerField()),
                ('shotpower', models.IntegerField()),
                ('slidingtackle', models.IntegerField()),
                ('sprintspeed', models.IntegerField()),
                ('standingtackle', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('vision', models.IntegerField()),
                ('volleys', models.IntegerField()),
                ('weakFoot', models.IntegerField()),
                ('atkWorkRate', models.CharField(max_length=100)),
                ('defWorkRate', models.CharField(max_length=100)),
                ('playerType', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('isGK', models.NullBooleanField()),
                ('positionFull', models.CharField(max_length=100)),
                ('isSpecialType', models.NullBooleanField()),
                ('contracts', models.IntegerField(null=True)),
                ('fitness', models.IntegerField(null=True)),
                ('rawAttributeChemistryBonus', models.IntegerField(null=True)),
                ('isLoan', models.NullBooleanField()),
                ('squadPosition', models.CharField(max_length=100, null=True)),
                ('itemType', models.CharField(max_length=100)),
                ('discardValue', models.IntegerField(null=True)),
                ('card_id', models.CharField(max_length=100)),
                ('modelName', models.CharField(max_length=100)),
                ('baseId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
